[package]
name = "crt-term-gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.52.0"
glow = "0.12.3"
image = { version = "0.24.6", default-features = false, features = ["png", "jpeg"] }
